import { Signal, Drop, PriceHistory, SocialItem, AnalyticsData } from '@/types';

export const MOCK_SIGNALS: Signal[] = [
  {
    id: 'sig_001',
    itemName: 'Jordan 4 Bred Reimagined',
    brand: 'Jordan',
    category: 'sneakers',
    imageGradient: 'from-red-900 via-black to-red-950',
    buyPlatform: 'mercari',
    buyPrice: 198,
    sellPlatform: 'stockx',
    sellPrice: 267,
    fees: 28,
    profit: 41,
    roi: 20.7,
    confidence: 94,
    urgency: 'act_now',
    signalType: 'arbitrage',
    aiNarrative: 'This Jordan 4 Bred Reimagined is priced 27% below market average on Mercari. StockX last 5 sales averaged $271. Seller listed 2 hours ago — typical sell-through at this price is 4-6 hours. Social volume spiked 340% this week as hype cycle peaks.',
    socialScore: 87,
    tiktokMentions: 12400,
    isActive: true,
    size: '10',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: 'sig_002',
    itemName: 'Nike SB Dunk Low "Paris"',
    brand: 'Nike SB',
    category: 'sneakers',
    imageGradient: 'from-amber-800 via-stone-900 to-amber-950',
    buyPlatform: 'ebay',
    buyPrice: 1240,
    sellPlatform: 'goat',
    sellPrice: 1580,
    fees: 158,
    profit: 182,
    roi: 14.7,
    confidence: 88,
    urgency: 'within_48hrs',
    signalType: 'arbitrage',
    aiNarrative: 'Paris Dunk consistently outperforms market expectations. eBay listing showing "Buy It Now" at $1,240 — 21% below GOAT market price. Seller ratings indicate quick flip. Art exhibition collab makes this a perennial grail with stable demand floor.',
    socialScore: 76,
    tiktokMentions: 8900,
    isActive: true,
    size: '9',
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
  },
  {
    id: 'sig_003',
    itemName: 'Supreme Box Logo Hoodie FW24',
    brand: 'Supreme',
    category: 'streetwear',
    imageGradient: 'from-red-700 via-red-900 to-black',
    buyPlatform: 'grailed',
    buyPrice: 340,
    sellPlatform: 'stockx',
    sellPrice: 485,
    fees: 49,
    profit: 96,
    roi: 28.2,
    confidence: 91,
    urgency: 'act_now',
    signalType: 'arbitrage',
    aiNarrative: 'Grailed listing priced below recent comps — FW24 BOGO hoodies typically move at $460-510 on StockX. Grailed seller accepted best offer of $340. Current StockX last sale: $491. Drop-off in supply will push prices up into weekend.',
    socialScore: 92,
    tiktokMentions: 18700,
    isActive: true,
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
  },
  {
    id: 'sig_004',
    itemName: 'Yeezy 350 V2 "Bone"',
    brand: 'Adidas',
    category: 'sneakers',
    imageGradient: 'from-stone-700 via-stone-900 to-stone-950',
    buyPlatform: 'mercari',
    buyPrice: 178,
    sellPlatform: 'goat',
    sellPrice: 235,
    fees: 24,
    profit: 33,
    roi: 18.5,
    confidence: 76,
    urgency: 'within_48hrs',
    signalType: 'arbitrage',
    aiNarrative: 'Bone colorway maintains consistent demand post-Yeezy controversy. GOAT authentication premium adds 15-20% over Mercari market. Recent Kanye social activity has nudged prices 8% upward this week. Window is closing as more sellers spot the spread.',
    socialScore: 61,
    tiktokMentions: 4200,
    isActive: true,
    size: '11',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
  },
  {
    id: 'sig_005',
    itemName: 'New Balance 2002R "Protection Pack"',
    brand: 'New Balance',
    category: 'sneakers',
    imageGradient: 'from-slate-700 via-slate-900 to-blue-950',
    buyPlatform: 'ebay',
    buyPrice: 142,
    sellPlatform: 'stockx',
    sellPrice: 198,
    fees: 20,
    profit: 36,
    roi: 25.4,
    confidence: 82,
    urgency: 'within_48hrs',
    signalType: 'arbitrage',
    aiNarrative: 'NB 2002R Protection Pack remains a consistent performer. eBay ungraded listing at $142 vs StockX authenticated market at $198. NB lifestyle positioning continues to attract luxury streetwear adjacent buyers — floor price has held for 6 months.',
    socialScore: 54,
    tiktokMentions: 3100,
    isActive: true,
    size: '10.5',
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
  },
  {
    id: 'sig_006',
    itemName: 'Pokemon Base Set Charizard PSA 9',
    brand: 'Pokemon TCG',
    category: 'trading_cards',
    imageGradient: 'from-orange-700 via-red-900 to-orange-950',
    buyPlatform: 'ebay',
    buyPrice: 2800,
    sellPlatform: 'mercari',
    sellPrice: 3400,
    fees: 340,
    profit: 260,
    roi: 9.3,
    confidence: 79,
    urgency: 'watch',
    signalType: 'price_prediction',
    aiNarrative: 'Base Set Charizard PSA 9 showing BIN price dip on eBay. Mercari comps over last 30 days averaged $3,280. Pokemon 25th anniversary campaigns keep driving renewed interest. PSA submission backlog reduction has increased authenticated supply but not enough to close the gap.',
    socialScore: 83,
    tiktokMentions: 22000,
    isActive: true,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
  },
  {
    id: 'sig_007',
    itemName: 'Jordan 1 High "Chicago Lost & Found"',
    brand: 'Jordan',
    category: 'sneakers',
    imageGradient: 'from-red-800 via-black to-red-900',
    buyPlatform: 'grailed',
    buyPrice: 310,
    sellPlatform: 'stockx',
    sellPrice: 390,
    fees: 39,
    profit: 41,
    roi: 13.2,
    confidence: 85,
    urgency: 'within_48hrs',
    signalType: 'arbitrage',
    aiNarrative: 'Lost & Found Chicago maintains blue chip status in Jordan 1 market. Grailed listing with no bids at $310 — immediate BIN opportunity. StockX 30-day average: $387. Distressed aged aesthetic means condition grading less scrutinized, making cross-platform arbitrage cleaner.',
    socialScore: 71,
    tiktokMentions: 6800,
    isActive: true,
    size: '9.5',
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
  },
  {
    id: 'sig_008',
    itemName: 'Stüssy 8-Ball Fleece',
    brand: 'Stüssy',
    category: 'streetwear',
    imageGradient: 'from-blue-800 via-blue-950 to-black',
    buyPlatform: 'mercari',
    buyPrice: 195,
    sellPlatform: 'grailed',
    sellPrice: 280,
    fees: 28,
    profit: 57,
    roi: 29.2,
    confidence: 78,
    urgency: 'within_48hrs',
    signalType: 'social_momentum',
    aiNarrative: 'Stüssy 8-Ball Fleece experiencing renewed demand from coastal streetwear community. Instagram accounts with 100K+ followers posted fits in last 48hrs. Mercari undervalues legacy Stüssy — Grailed buyers understand provenance premium. Q4 fleece season timing amplifies this signal.',
    socialScore: 78,
    tiktokMentions: 9200,
    isActive: true,
    createdAt: new Date(Date.now() - 7 * 60 * 60 * 1000),
  },
  {
    id: 'sig_009',
    itemName: 'Nike Air Max 1 "Patta Waves"',
    brand: 'Nike',
    category: 'sneakers',
    imageGradient: 'from-teal-800 via-slate-900 to-teal-950',
    buyPlatform: 'ebay',
    buyPrice: 398,
    sellPlatform: 'stockx',
    sellPrice: 520,
    fees: 52,
    profit: 70,
    roi: 17.6,
    confidence: 87,
    urgency: 'within_48hrs',
    signalType: 'arbitrage',
    aiNarrative: 'Patta collaboration commands consistent 30-35% premium over retail. eBay listing at $398 represents 23.5% discount vs StockX. Patta brand equity continues to expand into non-Dutch markets — American buyers discovering European collaborations drives steady demand uplift.',
    socialScore: 68,
    tiktokMentions: 5600,
    isActive: true,
    size: '10',
    createdAt: new Date(Date.now() - 9 * 60 * 60 * 1000),
  },
  {
    id: 'sig_010',
    itemName: 'Fear of God Essentials Hoodie',
    brand: 'FOG Essentials',
    category: 'streetwear',
    imageGradient: 'from-stone-700 via-stone-900 to-stone-950',
    buyPlatform: 'mercari',
    buyPrice: 78,
    sellPlatform: 'grailed',
    sellPrice: 125,
    fees: 13,
    profit: 34,
    roi: 43.6,
    confidence: 71,
    urgency: 'watch',
    signalType: 'arbitrage',
    aiNarrative: 'Essentials commands meaningful Grailed premium over Mercari due to buyer demographics. Target/Essentials collab drops maintaining cultural relevance. Low price point makes volume plays viable. Multiple colorways available — Taupe and Cream outperform Black on Grailed by 18%.',
    socialScore: 55,
    tiktokMentions: 14300,
    isActive: true,
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
  },
  {
    id: 'sig_011',
    itemName: 'Adidas Samba OG',
    brand: 'Adidas',
    category: 'sneakers',
    imageGradient: 'from-white/10 via-slate-900 to-slate-950',
    buyPlatform: 'ebay',
    buyPrice: 95,
    sellPlatform: 'goat',
    sellPrice: 145,
    fees: 15,
    profit: 35,
    roi: 36.8,
    confidence: 73,
    urgency: 'watch',
    signalType: 'social_momentum',
    aiNarrative: 'Samba OG defying "dead trend" narratives — GOAT premium reflects authenticated market confidence. eBay casual sellers underpricing as they don\'t track authenticated platforms. White/Black colorway specifically showing resilience. Volume opportunity here given $95 entry point.',
    socialScore: 82,
    tiktokMentions: 31000,
    isActive: true,
    size: '9',
    createdAt: new Date(Date.now() - 14 * 60 * 60 * 1000),
  },
  {
    id: 'sig_012',
    itemName: 'NBA Panini Prizm Wembanyama RC',
    brand: 'Panini',
    category: 'trading_cards',
    imageGradient: 'from-purple-800 via-purple-950 to-black',
    buyPlatform: 'ebay',
    buyPrice: 185,
    sellPlatform: 'mercari',
    sellPrice: 245,
    fees: 25,
    profit: 35,
    roi: 18.9,
    confidence: 83,
    urgency: 'within_48hrs',
    signalType: 'price_prediction',
    aiNarrative: 'Wembanyama performance trajectory remains exceptional — rookie card market follows on-court output with 3-4 week lag. Prizm Base RC PSA 10 candidates at $185 represent entry point before performance-driven repricing. Spurs playoff positioning by February could 2x this floor.',
    socialScore: 89,
    tiktokMentions: 17800,
    isActive: true,
    createdAt: new Date(Date.now() - 10 * 60 * 60 * 1000),
  },
  {
    id: 'sig_013',
    itemName: 'Bape 1st Camo Shark Hoodie',
    brand: 'Bape',
    category: 'streetwear',
    imageGradient: 'from-green-800 via-green-950 to-black',
    buyPlatform: 'ebay',
    buyPrice: 420,
    sellPlatform: 'grailed',
    sellPrice: 580,
    fees: 58,
    profit: 102,
    roi: 24.3,
    confidence: 80,
    urgency: 'within_48hrs',
    signalType: 'arbitrage',
    aiNarrative: 'Bape Shark Hoodies maintain cult following but eBay buyers consistently undervalue relative to Grailed where demographic overlap with Supreme buyers exists. Green Camo specifically outperforms Blue/Red on Grailed. Japanese market supply dip from yen volatility supporting price floor.',
    socialScore: 63,
    tiktokMentions: 7400,
    isActive: true,
    createdAt: new Date(Date.now() - 16 * 60 * 60 * 1000),
  },
  {
    id: 'sig_014',
    itemName: 'Jordan 11 "Cherry"',
    brand: 'Jordan',
    category: 'sneakers',
    imageGradient: 'from-red-700 via-black to-red-900',
    buyPlatform: 'mercari',
    buyPrice: 215,
    sellPlatform: 'stockx',
    sellPrice: 285,
    fees: 29,
    profit: 41,
    roi: 19.1,
    confidence: 89,
    urgency: 'act_now',
    signalType: 'arbitrage',
    aiNarrative: 'Jordan 11 Cherry priced aggressively on Mercari — possibly motivated seller. StockX 72-hour sales volume up 40% as holiday buying season begins. Jordan 11 Christmas tradition amplifies demand. This specific size (10) in DS condition at $215 is a clear market inefficiency.',
    socialScore: 76,
    tiktokMentions: 11200,
    isActive: true,
    size: '10',
    createdAt: new Date(Date.now() - 1.5 * 60 * 60 * 1000),
  },
  {
    id: 'sig_015',
    itemName: 'Chrome Hearts Trucker Hat',
    brand: 'Chrome Hearts',
    category: 'streetwear',
    imageGradient: 'from-gray-700 via-gray-900 to-black',
    buyPlatform: 'ebay',
    buyPrice: 285,
    sellPlatform: 'grailed',
    sellPrice: 420,
    fees: 42,
    profit: 93,
    roi: 32.6,
    confidence: 74,
    urgency: 'watch',
    signalType: 'arbitrage',
    aiNarrative: 'Chrome Hearts hardware accessories outperform broader luxury resale market. eBay listing without CH authentication documentation — Grailed buyers more forgiving of provenance gaps for accessories. CHH trucker hat specific model confirmed with cross-reference. Risk: authentication scrutiny at sale.',
    socialScore: 69,
    tiktokMentions: 5800,
    isActive: true,
    createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000),
  },
  {
    id: 'sig_016',
    itemName: 'Nike Dunk Low "Panda"',
    brand: 'Nike',
    category: 'sneakers',
    imageGradient: 'from-white/5 via-slate-900 to-black',
    buyPlatform: 'mercari',
    buyPrice: 88,
    sellPlatform: 'stockx',
    sellPrice: 125,
    fees: 13,
    profit: 24,
    roi: 27.3,
    confidence: 68,
    urgency: 'watch',
    signalType: 'arbitrage',
    aiNarrative: 'Panda Dunk market has softened from 2022 peak but authenticated platforms still command 30-40% over casual resellers. High volume opportunity given price accessibility. Multiple sizes available — 9.5 and 10.5 showing highest spreads. Consistent performer for new resellers building volume.',
    socialScore: 45,
    tiktokMentions: 28000,
    isActive: true,
    size: '10',
    createdAt: new Date(Date.now() - 20 * 60 * 60 * 1000),
  },
  {
    id: 'sig_017',
    itemName: 'One Piece TCG Manga Rare Luffy',
    brand: 'Bandai',
    category: 'trading_cards',
    imageGradient: 'from-yellow-700 via-orange-900 to-red-950',
    buyPlatform: 'ebay',
    buyPrice: 380,
    sellPlatform: 'mercari',
    sellPrice: 520,
    fees: 52,
    profit: 88,
    roi: 23.2,
    confidence: 86,
    urgency: 'within_48hrs',
    signalType: 'social_momentum',
    aiNarrative: 'One Piece TCG Manga Rare Luffy demand accelerating ahead of new anime arc coverage. Japanese domestic prices up 15% this month. US market 3-4 week lag behind JP trends. Netflix original series viewers converting to TCG buyers at record rates. PSA grading queue for OP cards now 45 days — raw card window is now.',
    socialScore: 91,
    tiktokMentions: 24600,
    isActive: true,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
  },
  {
    id: 'sig_018',
    itemName: 'ASICS Gel-Lyte III "Kith Palette"',
    brand: 'ASICS x Kith',
    category: 'sneakers',
    imageGradient: 'from-cyan-800 via-slate-900 to-cyan-950',
    buyPlatform: 'grailed',
    buyPrice: 225,
    sellPlatform: 'stockx',
    sellPrice: 320,
    fees: 32,
    profit: 63,
    roi: 28.0,
    confidence: 77,
    urgency: 'within_48hrs',
    signalType: 'arbitrage',
    aiNarrative: 'Kith collab recognition drives StockX premium over Grailed where ASICS heritage buyers dominate. Gel-Lyte III has seen 22% price appreciation over 90 days as Y2K revival sustains. Kith brand positioning in luxury tier justifies authenticated platform premium. Clean DS pair opportunity.',
    socialScore: 58,
    tiktokMentions: 3900,
    isActive: true,
    size: '10',
    createdAt: new Date(Date.now() - 11 * 60 * 60 * 1000),
  },
  {
    id: 'sig_019',
    itemName: 'Palace Tri-Ferg Tee',
    brand: 'Palace',
    category: 'streetwear',
    imageGradient: 'from-yellow-700 via-yellow-950 to-black',
    buyPlatform: 'ebay',
    buyPrice: 85,
    sellPlatform: 'grailed',
    sellPrice: 145,
    fees: 15,
    profit: 45,
    roi: 52.9,
    confidence: 72,
    urgency: 'watch',
    signalType: 'arbitrage',
    aiNarrative: 'Palace Tri-Ferg Tees consistently undervalued on eBay vs Grailed. UK buyers don\'t track US Grailed prices. FW24 colorway matches current seasonal palette. Palace brand heat with Reebok collabs maintaining streetwear relevance. High ROI but lower absolute dollar amount — good for volume stacking.',
    socialScore: 52,
    tiktokMentions: 4700,
    isActive: true,
    createdAt: new Date(Date.now() - 22 * 60 * 60 * 1000),
  },
  {
    id: 'sig_020',
    itemName: 'Off-White Diagonal Arrows Tee',
    brand: 'Off-White',
    category: 'streetwear',
    imageGradient: 'from-yellow-600 via-yellow-950 to-black',
    buyPlatform: 'grailed',
    buyPrice: 180,
    sellPlatform: 'stockx',
    sellPrice: 260,
    fees: 26,
    profit: 54,
    roi: 30.0,
    confidence: 69,
    urgency: 'watch',
    signalType: 'sell_signal',
    aiNarrative: 'OFF-WHITE Virgil archive pieces seeing renewed demand post-retrospective exhibitions. Diagonal Arrows specifically referenced in recent editorial coverage. Grailed seller pricing based on 2022 market data — StockX now commands premium for authentication. SELL signal on existing inventory above $220.',
    socialScore: 61,
    tiktokMentions: 6200,
    isActive: true,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
  {
    id: 'sig_021',
    itemName: 'MTG Black Lotus (Unlimited)',
    brand: 'Magic The Gathering',
    category: 'trading_cards',
    imageGradient: 'from-indigo-900 via-black to-purple-950',
    buyPlatform: 'ebay',
    buyPrice: 4200,
    sellPlatform: 'mercari',
    sellPrice: 5400,
    fees: 540,
    profit: 660,
    roi: 15.7,
    confidence: 65,
    urgency: 'watch',
    signalType: 'price_prediction',
    aiNarrative: 'Unlimited Black Lotus pricing showing volatility — eBay listing at $4,200 represents 22% below recent comparable sales. MTG30 Anniversary event coverage increasing collector awareness. Verify condition carefully — MP vs LP condition gap is significant at this price point. Authentication recommended before transaction.',
    socialScore: 44,
    tiktokMentions: 8900,
    isActive: true,
    createdAt: new Date(Date.now() - 30 * 60 * 60 * 1000),
  },
  {
    id: 'sig_022',
    itemName: 'Garbage Pail Kids OS1 Adam Bomb PSA 8',
    brand: 'Topps',
    category: 'collectibles',
    imageGradient: 'from-green-800 via-black to-green-950',
    buyPlatform: 'ebay',
    buyPrice: 145,
    sellPlatform: 'mercari',
    sellPrice: 210,
    fees: 21,
    profit: 44,
    roi: 30.3,
    confidence: 71,
    urgency: 'watch',
    signalType: 'arbitrage',
    aiNarrative: 'GPK OS1 Adam Bomb PSA 8 showing consistent spread between eBay and Mercari due to platform audience differences. Nostalgia cycle reaching peak — 80s/90s children with disposable income driving vintage TCG demand. PSA 8 sweet spot for value vs PSA 9 premium jump.',
    socialScore: 48,
    tiktokMentions: 2300,
    isActive: true,
    createdAt: new Date(Date.now() - 32 * 60 * 60 * 1000),
  },
  {
    id: 'sig_023',
    itemName: 'Jordan 4 "Military Black"',
    brand: 'Jordan',
    category: 'sneakers',
    imageGradient: 'from-gray-800 via-black to-gray-950',
    buyPlatform: 'mercari',
    buyPrice: 175,
    sellPlatform: 'goat',
    sellPrice: 235,
    fees: 24,
    profit: 36,
    roi: 20.6,
    confidence: 84,
    urgency: 'within_48hrs',
    signalType: 'arbitrage',
    aiNarrative: 'Military Black Jordan 4 holds strong across size runs. Mercari seller appears to be clearing inventory — 3 pairs listed, best spread on size 11. GOAT authentication adds significant buyer confidence premium. Military colorway anniversary marketing from Jordan Brand maintaining cultural relevance.',
    socialScore: 65,
    tiktokMentions: 9800,
    isActive: true,
    size: '11',
    createdAt: new Date(Date.now() - 4.5 * 60 * 60 * 1000),
  },
  {
    id: 'sig_024',
    itemName: 'Carhartt WIP OG Active Jacket',
    brand: 'Carhartt WIP',
    category: 'streetwear',
    imageGradient: 'from-amber-900 via-brown-950 to-amber-950',
    buyPlatform: 'ebay',
    buyPrice: 95,
    sellPlatform: 'grailed',
    sellPrice: 165,
    fees: 17,
    profit: 53,
    roi: 55.8,
    confidence: 67,
    urgency: 'watch',
    signalType: 'social_momentum',
    aiNarrative: 'Carhartt WIP experiencing luxury workwear renaissance — Instagram algorithm surfacing vintage pieces to 18-24 demographic. OG Active Jacket in Hamilton Brown specifically trending. eBay listings from traditional workwear buyers unaware of streetwear premium. Grailed consignment plays well here.',
    socialScore: 72,
    tiktokMentions: 19400,
    isActive: true,
    createdAt: new Date(Date.now() - 26 * 60 * 60 * 1000),
  },
  {
    id: 'sig_025',
    itemName: 'Nike Air Max 1 "Travis Scott"',
    brand: 'Nike x Travis Scott',
    category: 'sneakers',
    imageGradient: 'from-orange-900 via-brown-950 to-orange-950',
    buyPlatform: 'grailed',
    buyPrice: 890,
    sellPlatform: 'stockx',
    sellPrice: 1180,
    fees: 118,
    profit: 172,
    roi: 19.3,
    confidence: 92,
    urgency: 'act_now',
    signalType: 'arbitrage',
    aiNarrative: 'Travis Scott Air Max 1 grail pair listed on Grailed at below-market. Travis concert season driving renewed demand for all Cactus Jack collabs. StockX 7-day trend up 12%. Grailed seller has 100% feedback — legitimate pair. Act within 2 hours as algorithmic price discovery will close this gap.',
    socialScore: 94,
    tiktokMentions: 34200,
    isActive: true,
    size: '10',
    createdAt: new Date(Date.now() - 0.5 * 60 * 60 * 1000),
  },
  {
    id: 'sig_026',
    itemName: 'Bottega Veneta Pouch',
    brand: 'Bottega Veneta',
    category: 'vintage',
    imageGradient: 'from-amber-800 via-amber-950 to-brown-900',
    buyPlatform: 'ebay',
    buyPrice: 680,
    sellPlatform: 'grailed',
    sellPrice: 920,
    fees: 92,
    profit: 148,
    roi: 21.8,
    confidence: 73,
    urgency: 'watch',
    signalType: 'arbitrage',
    aiNarrative: 'BV Pouch luxury resale market stabilizing after 2023 peak. eBay listing in "intrecciato" weave, Caramel colorway — highest demand variant. Grailed luxury authentication premium significant. Daniel Lee-era pieces command premium over current Matthieu Blazy era among collectors who track design continuity.',
    socialScore: 57,
    tiktokMentions: 3400,
    isActive: true,
    createdAt: new Date(Date.now() - 36 * 60 * 60 * 1000),
  },
  {
    id: 'sig_027',
    itemName: 'Kith x Versace Crewneck',
    brand: 'Kith x Versace',
    category: 'streetwear',
    imageGradient: 'from-yellow-700 via-black to-yellow-900',
    buyPlatform: 'grailed',
    buyPrice: 340,
    sellPlatform: 'stockx',
    sellPrice: 460,
    fees: 46,
    profit: 74,
    roi: 21.8,
    confidence: 81,
    urgency: 'within_48hrs',
    signalType: 'arbitrage',
    aiNarrative: 'Kith x Versace collab maintaining strong secondary market. Grailed listing at retail-adjacent pricing — seller appears to be early buyer unfamiliar with secondary appreciation. StockX Medusa logo collabs consistently outperform non-collab Versace. FW24 styling editorial featuring this piece surfaced 3 days ago.',
    socialScore: 74,
    tiktokMentions: 8100,
    isActive: true,
    createdAt: new Date(Date.now() - 8.5 * 60 * 60 * 1000),
  },
  {
    id: 'sig_028',
    itemName: 'iPhone 15 Pro Sealed Box',
    brand: 'Apple',
    category: 'electronics',
    imageGradient: 'from-gray-600 via-gray-950 to-black',
    buyPlatform: 'mercari',
    buyPrice: 880,
    sellPlatform: 'ebay',
    sellPrice: 1050,
    fees: 105,
    profit: 65,
    roi: 7.4,
    confidence: 62,
    urgency: 'watch',
    signalType: 'arbitrage',
    aiNarrative: 'Sealed Apple products command meaningful eBay premium over Mercari — authentication confidence and buyer protection explain spread. Q4 gift buying season amplifying demand. However, iPhone 16 release timeline creates ceiling risk. Black Titanium 256GB specifically showing strongest differential. Lower confidence due to market timing risk.',
    socialScore: 38,
    tiktokMentions: 1200,
    isActive: true,
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000),
  },
  {
    id: 'sig_029',
    itemName: 'Stüssy x Nike Air Huarache',
    brand: 'Stüssy x Nike',
    category: 'sneakers',
    imageGradient: 'from-pink-800 via-pink-950 to-black',
    buyPlatform: 'ebay',
    buyPrice: 265,
    sellPlatform: 'stockx',
    sellPrice: 365,
    fees: 37,
    profit: 63,
    roi: 23.8,
    confidence: 88,
    urgency: 'within_48hrs',
    signalType: 'arbitrage',
    aiNarrative: 'Stüssy x Nike Huarache has appreciated 28% since release. eBay listing appears to be flip gone wrong — seller acquired at higher price, now pricing at cost. StockX buyer premium for Nike authentication. Stüssy streetwear credibility continues driving this collab above Nike-only Huarache market.',
    socialScore: 71,
    tiktokMentions: 7600,
    isActive: true,
    size: '9.5',
    createdAt: new Date(Date.now() - 6.5 * 60 * 60 * 1000),
  },
  {
    id: 'sig_030',
    itemName: 'Supreme x The North Face Jacket',
    brand: 'Supreme x TNF',
    category: 'streetwear',
    imageGradient: 'from-red-700 via-black to-red-950',
    buyPlatform: 'grailed',
    buyPrice: 480,
    sellPlatform: 'stockx',
    sellPrice: 680,
    fees: 68,
    profit: 132,
    roi: 27.5,
    confidence: 90,
    urgency: 'act_now',
    signalType: 'arbitrage',
    aiNarrative: 'Sup x TNF Mountain Jacket is a perennial. Grailed listing at $480 for FW24 Nuptse variant — 29% below StockX. November through February demand cycle pushes TNF prices up every year without fail. This collab specifically outperforms because both brands maintain premium positioning. 4 hour window before algorithmic repricing.',
    socialScore: 88,
    tiktokMentions: 16800,
    isActive: true,
    createdAt: new Date(Date.now() - 0.75 * 60 * 60 * 1000),
  },
];

export const MOCK_DROPS: Drop[] = [
  {
    id: 'drop_001',
    itemName: 'Jordan 4 "Vivid Sulfur"',
    brand: 'Jordan',
    category: 'sneakers',
    imageGradient: 'from-yellow-600 via-yellow-950 to-black',
    retailPrice: 210,
    predictedResaleMin: 290,
    predictedResaleMax: 340,
    predictedProfit: 95,
    releasePlatform: 'Nike SNKRS',
    releaseDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    difficultyRating: 'hard',
    aiAnalysis: 'Jordan 4 Vivid Sulfur represents a fresh colorway departure for the silhouette. Yellow/Gold colorways historically outperform in secondary markets due to visual distinctiveness. Predicted W rate on SNKRS: ~8%. Resale trajectory: $310-340 in first 72 hours, stabilizing at $290-310 within 2 weeks.',
    createdAt: new Date(),
  },
  {
    id: 'drop_002',
    itemName: 'New Balance 1906R "Protection Pack Grey"',
    brand: 'New Balance',
    category: 'sneakers',
    imageGradient: 'from-gray-600 via-gray-950 to-black',
    retailPrice: 150,
    predictedResaleMin: 185,
    predictedResaleMax: 220,
    predictedProfit: 52,
    releasePlatform: 'NB Website + Select Retailers',
    releaseDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    difficultyRating: 'medium',
    aiAnalysis: 'NB 1906R Protection Pack Grey following success of 2002R Protection Pack. Grey is the highest demand colorway in NB lifestyle. Expected to sell out online within 45 minutes. Multiple retailer release increases access — DTLR, Foot Locker, Bodega all confirmed. Better W rate than SNKRS releases.',
    createdAt: new Date(),
  },
  {
    id: 'drop_003',
    itemName: 'Supreme FW24 Week 14 Box Logo',
    brand: 'Supreme',
    category: 'streetwear',
    imageGradient: 'from-red-700 via-red-950 to-black',
    retailPrice: 168,
    predictedResaleMin: 520,
    predictedResaleMax: 650,
    predictedProfit: 432,
    releasePlatform: 'Supreme Online + In-Store',
    releaseDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
    difficultyRating: 'near_impossible',
    aiAnalysis: 'FW24 Box Logo confirmed — leaks show unique colorway not seen since 2019. Near-impossible online: Supreme bot protection means <1% W rate for non-botters. In-store lines will begin 48hrs prior. Secondary market opens at 3.5x retail minimum. Red/Black BOGO hoodies commanding $580-650 in pre-sale market.',
    createdAt: new Date(),
  },
  {
    id: 'drop_004',
    itemName: 'Nike Dunk Low "University Blue"',
    brand: 'Nike',
    category: 'sneakers',
    imageGradient: 'from-blue-700 via-blue-950 to-black',
    retailPrice: 110,
    predictedResaleMin: 145,
    predictedResaleMax: 175,
    predictedProfit: 42,
    releasePlatform: 'Nike SNKRS + Foot Locker',
    releaseDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    difficultyRating: 'medium',
    aiAnalysis: 'University Blue Dunk represents classic colorway with consistent demand. Carolina Blue colorways historically perform well in UNC/Duke markets. Foot Locker allocation increases access. Predicted first-day premium: $145-175. Volume opportunity — not a trophy flip but reliable margin.',
    createdAt: new Date(),
  },
  {
    id: 'drop_005',
    itemName: 'Kith x Coca-Cola Collab',
    brand: 'Kith',
    category: 'streetwear',
    imageGradient: 'from-red-800 via-black to-red-900',
    retailPrice: 185,
    predictedResaleMin: 280,
    predictedResaleMax: 380,
    predictedProfit: 165,
    releasePlatform: 'Kith.com + Kith Stores',
    releaseDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000),
    difficultyRating: 'hard',
    aiAnalysis: 'Kith brand collabs consistently 2x retail in secondary. Coca-Cola licensing adds nostalgia factor. Kith drops favor early-morning EST buyers — 11am drops sell out in under 60 seconds online. In-store lottery likely at NYC flagship. Predicted strongest performer: Coke Red Crewneck at $320-380.',
    createdAt: new Date(),
  },
  {
    id: 'drop_006',
    itemName: 'Jordan 1 High OG "Taxi"',
    brand: 'Jordan',
    category: 'sneakers',
    imageGradient: 'from-yellow-700 via-black to-yellow-900',
    retailPrice: 180,
    predictedResaleMin: 240,
    predictedResaleMax: 290,
    predictedProfit: 85,
    releasePlatform: 'Nike SNKRS',
    releaseDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
    difficultyRating: 'hard',
    aiAnalysis: 'Jordan 1 High Taxi Yellow colorway accessing pent-up demand for bright OG J1 colorways. SNKRS drop format likely FCFS or Draw. Yellow/Black J1s have historically 50-70% appreciation in first month. Predicted market: $270-290 day-of, settling at $240-260 after 2 weeks.',
    createdAt: new Date(),
  },
  {
    id: 'drop_007',
    itemName: 'Adidas Gazelle Indoor "Collegiate Green"',
    brand: 'Adidas',
    category: 'sneakers',
    imageGradient: 'from-green-700 via-green-950 to-black',
    retailPrice: 90,
    predictedResaleMin: 105,
    predictedResaleMax: 130,
    predictedProfit: 27,
    releasePlatform: 'Adidas.com + SNS',
    releaseDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000),
    difficultyRating: 'easy',
    aiAnalysis: 'Gazelle Indoor still riding the Adidas terrace revival wave. Collegiate Green specifically showing strong European pre-sale interest. Easy cop — Adidas.com rarely sells out lifestyle footwear in first day. Lower profit ceiling but nearly guaranteed W. Good for beginners building capital.',
    createdAt: new Date(),
  },
  {
    id: 'drop_008',
    itemName: 'Corteiz x Nike Air Max 95',
    brand: 'Corteiz x Nike',
    category: 'sneakers',
    imageGradient: 'from-olive-700 via-black to-olive-950',
    retailPrice: 175,
    predictedResaleMin: 650,
    predictedResaleMax: 850,
    predictedProfit: 625,
    releasePlatform: 'Corteiz Drop (Social Media Only)',
    releaseDate: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000),
    difficultyRating: 'near_impossible',
    aiAnalysis: 'Corteiz drops are chaotic by design — location announced 30 minutes before drop via Instagram. In-person only likely. Online allocation 0-500 units globally. Secondary market already trading at $680-720 on pre-sale. This is a trophy flip — if you can get one. Social signal score 97/100.',
    createdAt: new Date(),
  },
  {
    id: 'drop_009',
    itemName: 'Stone Island x Vans Vault',
    brand: 'Stone Island x Vans',
    category: 'sneakers',
    imageGradient: 'from-orange-800 via-orange-950 to-black',
    retailPrice: 145,
    predictedResaleMin: 210,
    predictedResaleMax: 270,
    predictedProfit: 95,
    releasePlatform: 'Stone Island Stores + Vans Vault',
    releaseDate: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000),
    difficultyRating: 'medium',
    aiAnalysis: 'Stone Island x Vans represents high-low collaboration with strong secondary following. Both brands have dedicated collector bases that rarely overlap — creating dual-market demand. SI compass badge on Vans specifically targeted at SI collectors who don\'t typically buy Vans. Cross-audience premium.',
    createdAt: new Date(),
  },
  {
    id: 'drop_010',
    itemName: 'Palace x Lacoste Polo',
    brand: 'Palace x Lacoste',
    category: 'streetwear',
    imageGradient: 'from-green-700 via-green-950 to-black',
    retailPrice: 195,
    predictedResaleMin: 320,
    predictedResaleMax: 420,
    predictedProfit: 185,
    releasePlatform: 'Palace Website + Stores',
    releaseDate: new Date(Date.now() + 11 * 24 * 60 * 60 * 1000),
    difficultyRating: 'hard',
    aiAnalysis: 'Palace x Lacoste collabs have been consistently strong performers — combining UK skate aesthetic with French preppy heritage creates broad demographic appeal. Previous collab (FW22) averaged 2.3x retail on secondary. Polo specific model at $195 retail predicted to trade at $340-420 based on colorway and size availability.',
    createdAt: new Date(),
  },
];

export function generatePriceHistory(
  itemName: string,
  platforms: string[],
  basePrice: number,
  days = 90
): PriceHistory[] {
  const history: PriceHistory[] = [];
  const now = new Date();

  platforms.forEach((platform, platformIdx) => {
    const platformMultiplier = [1, 1.15, 0.92, 0.88, 1.08][platformIdx] || 1;
    let price = basePrice * platformMultiplier;

    for (let i = days; i >= 0; i--) {
      const date = new Date(now.getTime() - i * 24 * 60 * 60 * 1000);
      const trend = 1 + (days - i) / days * 0.15;
      const noise = 1 + (Math.random() - 0.5) * 0.08;
      const spike = Math.random() > 0.93 ? 1 + Math.random() * 0.12 : 1;
      price = price * trend * noise * spike;
      price = Math.max(price, basePrice * 0.7);

      history.push({
        id: `ph_${itemName}_${platform}_${i}`,
        itemName,
        platform: platform as any,
        price: Math.round(price),
        recordedAt: date,
      });
    }
  });

  return history;
}

export const MOCK_PRICE_HISTORIES: Record<string, PriceHistory[]> = {
  'Jordan 4 Bred Reimagined': generatePriceHistory('Jordan 4 Bred Reimagined', ['stockx', 'goat', 'ebay', 'mercari'], 240),
  'Nike SB Dunk Low "Paris"': generatePriceHistory('Nike SB Dunk Low "Paris"', ['stockx', 'goat', 'ebay'], 1400),
  'Supreme Box Logo Hoodie FW24': generatePriceHistory('Supreme Box Logo Hoodie FW24', ['stockx', 'grailed', 'ebay'], 420),
  'Jordan 11 "Cherry"': generatePriceHistory('Jordan 11 "Cherry"', ['stockx', 'goat', 'mercari'], 250),
  'Nike Air Max 1 "Travis Scott"': generatePriceHistory('Nike Air Max 1 "Travis Scott"', ['stockx', 'grailed', 'goat'], 1000),
};

export const MOCK_ANALYTICS: AnalyticsData = {
  totalSignalsViewed: 847,
  signalsFlipped: 23,
  estimatedProfit: 3840,
  avgProfitPerFlip: 167,
  bestFlipProfit: 624,
  winRate: 78.3,
  categoryBreakdown: [
    { category: 'Sneakers', count: 340, profit: 1840 },
    { category: 'Streetwear', count: 210, profit: 980 },
    { category: 'Trading Cards', count: 180, profit: 720 },
    { category: 'Collectibles', count: 72, profit: 190 },
    { category: 'Vintage', count: 45, profit: 110 },
  ],
  platformComparison: [
    { platform: 'Mercari', underpriced: 847, avgDiscount: 22.3 },
    { platform: 'eBay', underpriced: 623, avgDiscount: 18.7 },
    { platform: 'Grailed', underpriced: 412, avgDiscount: 15.4 },
    { platform: 'StockX', underpriced: 89, avgDiscount: 8.2 },
    { platform: 'GOAT', underpriced: 67, avgDiscount: 6.8 },
  ],
  weeklyTrends: Array.from({ length: 28 }, (_, i) => ({
    date: new Date(Date.now() - (27 - i) * 24 * 60 * 60 * 1000).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }),
    signals: Math.floor(40 + Math.random() * 60),
    avgSpread: Math.floor(35 + Math.random() * 80),
  })),
  hotItems: [
    { name: 'Jordan 4 Bred Reimagined', signalCount: 24, avgProfit: 48 },
    { name: 'Travis Scott x Nike AM1', signalCount: 18, avgProfit: 172 },
    { name: 'Supreme BOGO FW24', signalCount: 16, avgProfit: 108 },
    { name: 'Wembanyama Prizm RC', signalCount: 14, avgProfit: 52 },
    { name: 'NB 2002R Protection Pack', signalCount: 12, avgProfit: 38 },
    { name: 'One Piece Manga Rare', signalCount: 11, avgProfit: 94 },
    { name: 'Carhartt WIP Active Jacket', signalCount: 9, avgProfit: 58 },
  ],
  socialMomentum: [
    { itemName: 'Jordan 4 Bred Reimagined', brand: 'Jordan', tiktokMentions: 12400, instagramEngagement: 84000, priceImpact: 12.3, trend: 'rising', currentPrice: 267 },
    { itemName: 'Adidas Samba OG', brand: 'Adidas', tiktokMentions: 31000, instagramEngagement: 210000, priceImpact: 8.7, trend: 'rising', currentPrice: 145 },
    { itemName: 'One Piece TCG Manga Rare', brand: 'Bandai', tiktokMentions: 24600, instagramEngagement: 156000, priceImpact: 18.4, trend: 'rising', currentPrice: 520 },
    { itemName: 'Supreme Box Logo FW24', brand: 'Supreme', tiktokMentions: 18700, instagramEngagement: 124000, priceImpact: 9.2, trend: 'stable', currentPrice: 485 },
    { itemName: 'Wembanyama Prizm RC', brand: 'Panini', tiktokMentions: 17800, instagramEngagement: 98000, priceImpact: 22.1, trend: 'rising', currentPrice: 245 },
    { itemName: 'Corteiz x Nike AM95', brand: 'Corteiz', tiktokMentions: 45200, instagramEngagement: 380000, priceImpact: 67.4, trend: 'rising', currentPrice: 720 },
    { itemName: 'Kith x Versace Crewneck', brand: 'Kith', tiktokMentions: 8100, instagramEngagement: 62000, priceImpact: 5.8, trend: 'stable', currentPrice: 460 },
    { itemName: 'Carhartt WIP OG Jacket', brand: 'Carhartt WIP', tiktokMentions: 19400, instagramEngagement: 142000, priceImpact: 15.6, trend: 'rising', currentPrice: 165 },
    { itemName: 'Jordan 11 Cherry', brand: 'Jordan', tiktokMentions: 11200, instagramEngagement: 74000, priceImpact: 11.3, trend: 'rising', currentPrice: 285 },
    { itemName: 'Off-White Diagonal Arrows Tee', brand: 'Off-White', tiktokMentions: 6200, instagramEngagement: 48000, priceImpact: -3.2, trend: 'falling', currentPrice: 260 },
  ],
};
